### ISSUE TITLE
Add clean and auto remove

### ISSUE THREAD

**Issue by wolfsea89** [rachuna-net-pl/rnp-tools-ansible-roles-installpackages#5]
```
- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
```
